spring:
  cache:
    type: caffeine
  caffeine:
    spec: maximumSize=100,expireAfterWrite=5m

resilience4j:
  retry:
    instances:
      githubClient:
        maxAttempts: 3
        waitDuration: 1s

logging:
  level:
    root: info
    org.springframework.web: debug
    org.springframework.boot: info
    org.springframework: error
    com.branchapp.github: debug
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"




